language: python

python:
  - "3.6"

sudo: required

os:
  - linux

script:
  - /bin/bash ./scripts/test_all_case.sh ./tests/tclist_all
  - /bin/bash ./scripts/check_code_style.sh

notifications:
  email:
    on_success: change
    on_failure: always
