language: python

jobs:
  include:
    - name: "CI on Windows/Python3.6"
      os: windows
      python: 3.6
    - name: "CI on MacOS/Python3.6"
      os: osx
      python: 3.6
    - name: "CI on Linux/Python3.6"
      os: linux
      python: 3.6
    - name: "CI on Linux/Python3.5"
      os: linux
      python: 3.5
    - name: "CI on Linux/Python2.7"
      os: linux
      python: 2.7

install:
  - pip install --upgrade paddlepaddle
  - pip install -r requirements.txt
  - pip install .

script:
  - if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then /bin/bash ./scripts/check_code_style.sh; fi
  - /bin/bash ./scripts/test_cml.sh
  - /bin/bash ./scripts/test_all_module.sh

notifications:
  email:
    on_success: change
    on_failure: always
