language: python

jobs:
  include:
    - name: "CI on Windows/Python3.6"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "CI on Linux/Python3.6"
      os: linux
      python: 3.6
    - name: "CI on Linux/Python3.5"
      os: linux
      python: 3.5
    - name: "CI on Linux/Python2.7"
      os: linux
      python: 2.7

env:
  - PYTHONPATH=${PWD}

install:
  - pip install --upgrade paddlepaddle
  - pip install -r requirements.txt

script:
  - if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then /bin/bash ./scripts/check_code_style.sh; fi
  - if [[ $TRAVIS_OS_NAME != "windows" ]]; then /bin/bash ./scripts/test_cml.sh
  - if [[ $TRAVIS_OS_NAME != "windows" ]]; then /bin/bash ./scripts/test_all_module.sh

notifications:
  email:
    on_success: change
    on_failure: always
